library {{.Name}}.models;
import 'package:arasu/resource/resource.dart';
/*auto generated by arasu framework please don't edit this block  */
//::pattern::part '+++replace_this+++.dart';
/*auto generated by arasu framework please don't edit this block  */
