library {{.Name}}.routes;
import 'package:arasu/resource/resource.dart';
import 'package:angular/angular.dart';
import 'package:angular/routing/module.dart';

/*auto generated by arasu framework please don't edit this block  */
//::pattern::part '+++replace_this+++.dart';
void controllers_routes(Router router, RouteViewFactory views) {
//::pattern::  +++replace_this+++_routes(router, views);
}  
/*auto generated by arasu framework please don't edit this block  */

class Routes extends Module {
  Routes() {
    bind(NgRoutingUsePushState, toValue: new NgRoutingUsePushState.value(false));
    bind(Db, toFactory: (v) {
      Db db = new Db();
      db.http = v.get(Http);
      return db;
    },inject:[Injector]);
  }
}
