#Created by Arasu Frameowrk at application creation
#feel free to edit 
name: {{.Name}}
description: A {{.Name}} web application
dependencies:
  angular: any
  arasu: any
  web_components: ">=0.8.0 <0.9.0"
  browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular
