library {{.Name}}.controllers;
import 'package:angular/angular.dart';

/*auto generated by arasu framework please don't edit this block  */
//::pattern::import 'package:{{.Name}}/controllers/+++replace_this+++/+++replace_this+++.dart';
void bind_all(Module m){
//::pattern::  bind_+++replace_this+++_actions(m);
}
/*auto generated by arasu framework please don't edit this block  */

class Controllers extends Module {
  Controllers() {
    bind_all(this);
  }
}
